name: 'Tweet when Labeled'

on:
  issues:
    types: labeled
  pull_request:
    types: labeled

permissions:
  contents: read
  issues: write

jobs:
  action:
    if: ${{ github.event.label.name == 'issue/tweet' }}
    runs-on: ubuntu-latest
    steps:
        - uses: tspascoal/get-user-teams-membership@v2
          id: checkUserMember
          with:
            username: ${{ github.actor }}
            organization: 'Equinox-IIIT-Lucknow'
            team: 'HOF Team'
            GITHUB_TOKEN: ${{ secrets.PAT }}
        - name: Check if it is issue
          if: ${{ github.event.issue }}
          run: echo ISSUE
        - name: Check if it is PR
          if: ${{ github.event.pull_request }}
          run: echo PULLREQUEST
        - name: Check the status  
          # if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
          run: echo ${{ steps.checkUserMember.outputs.isTeamMember }}
        # - name: Check if organization member
        #   id: is_organization_member
        #   uses: jamessingleton/is-organization-member@1.0.0
        #   with:
        #     organization: Equinox-IIIT-Lucknow
        #     username: ${{ github.event.issue.user.login }}
        #     token: ${{ github.token }}
        # - name: Print Output
        #   if: ${{ steps.is_organization_member.outputs.result == 'true' }}
        #   uses: ethomson/send-tweet-action@v1
        #   with:
        #     status: "Hello Twitter, Check this out - ${{ github.event.issue.html_url }} with the title ${{ github.event.issue.title }}"
        #     status: "Help wanted: "${{ github.event.issue.title }}" - ${{ github.event.issue.html_url }} #opensource"
        #     consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        #     consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        #     access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        #     access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}