name: 'Tweet when Labeled'

on:
  issues:
    types: labeled
  pull_request:
    types: labeled

permissions:
  contents: read
  issues: write

jobs:
  action:
    if: ${{ github.event.label.name == 'issue/tweet' }}
    runs-on: ubuntu-latest
    steps:
        - uses: tspascoal/get-user-teams-membership@v2
          id: checkUserMember
          with:
            username: ${{ github.actor }}
            organization: 'Equinox-IIIT-Lucknow'
            team: 'HOF Team'
            GITHUB_TOKEN: ${{ secrets.PAT }}
        # - name: Check the status  
        #   if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
        - name: Check if it is issue
          if: ${{ github.event.issue }} && ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
          uses: ethomson/send-tweet-action@v1
          with:
            status: "Help wanted on this issue: "${{ github.event.issue.title }}" - ${{ github.event.issue.html_url }}"
            consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
            consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
            access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        - name: Check if it is PR && ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
          if: ${{ github.event.pull_request }}
          uses: ethomson/send-tweet-action@v1
          with:
            status: "Help wanted: "${{ github.event.pull_request.title }}" - ${{ github.event.pull_request.html_url }}"
            consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
            consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
            access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          # run: echo ${{ steps.checkUserMember.outputs.isTeamMember }}
        # - name: Check if organization member
        #   id: is_organization_member
        #   uses: jamessingleton/is-organization-member@1.0.0
        #   with:
        #     organization: Equinox-IIIT-Lucknow
        #     username: ${{ github.event.issue.user.login }}
        #     token: ${{ github.token }}
        # - name: Print Output
        #   if: ${{ steps.is_organization_member.outputs.result == 'true' }}